str1=input("Enter string 1:")
str2=input("Enter string 2:")
concat=str1+" "+str2
print(concat)
#lower(), upper(), title(), swapcase(), capitalize(), casefold(), center(), count(), endswith(), find(), isalnum(), isdigit(), isnumeric(), isspace(), replace()
print("lower:",concat.lower())
print("upper:",concat.upper())
print("title:",concat.title())
print("swapcase:",concat.swapcase())
print("capitalize:",concat.capitalize())
print("casefold:",concat.casefold())
print("center:",concat.center(110))
print("count:",concat.count("a"))
print("endswith:",concat.endswith("a"))
print("find:",concat.find("a"))
print("isalnum:",concat.isalnum())
print("isdigit:",concat.isdigit())
print("isnumeric:",concat.isnumeric())
print("Replace:",concat.replace("a","A"))

