import pandas as pd
df = pd.read_csv("tips.csv")
print("First 5 Records")
print(df.head())
print("\nMissing Values:")
print(df.isnull().sum())
df = df.drop_duplicates() 
print("\nData Types:")
print(df.dtypes)
print("\nSummary Statistics:")
print(df.describe())
print("\nAverage Total Bill:")
print(df["total_bill"].mean())
print("\nAverage Tip:")
print(df["tip"].mean())
print("\nHighest Bill:")
print(df["total_bill"].max())
print("\nAverage Tip by Gender:")
print(df.groupby("sex")["tip"].mean())
print("\nAverage Bill by Day:")
print(df.groupby("day")["total_bill"].mean())
print("\nAverage Tip by Smoker Status:")
print(df.groupby("smoker")["tip"].mean())
print("\nTotal Sales by Day:")
print(df.groupby("day")["total_bill"].sum())
print("\nRecord with Highest Tip:")
print(df.loc[df["tip"].idxmax()])
